### ISSUE TITLE
Create typename variable when generating models.py

### ISSUE THREAD

**Issue by ikben** [aws-cloudformation/cloudformation-cli-python-plugin#54]
If you want to throw an already exist error, you currently do:

```
raise exceptions.AlreadyExists('MyOrg::Foo::Bar', model.BarId)
```

It would be nice if this could be:
```
from models import resource_type
raise exceptions.AlreadyExists(resource_type, model.BarId)
```

or even
```
raise exceptions.AlreadyExists(model)
```

**Comment by tobywf** [comment]
that makes sense, we'll need the type name for metrics publishing anyway so this would be a great enhancement.

just need to find a home for it. since it's very difficult to change the type name after initialisation of the codebase, i'd be inclined to add it to `handlers.py` as a constant and pass it to `Resource` when we initialise that.
